### PR TITLE
2.3.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
* #870 - fix dispose for level-restricted sinks
 * #852 - fix dictionary capturing when key/value are anonymous types
 * #835 - avoid `RemotingException` via `LogContext`
 * #855 -  allow custom enum rendering (better `ICustomFormatter` support
 * #841 - `audit-to` in key-value settings

### CODE REVIEW

**Comment by nblumhardt** [comment]
I think it's time to get this one out the door - @serilog/reviewers-core any final thoughts?

**Comment by adamchester** [comment]
LGTM

**Comment by nblumhardt** [comment]
Thanks @adamchester

**Comment by merbla** [comment]
All good here.  Changes.md?

**Comment by nblumhardt** [comment]
@merbla snuck it in yesterday :-) https://github.com/serilog/serilog/blob/dev/CHANGES.md

**Pull request merged**
