### PR TITLE
dotnet cli preview2 and core RTM

### PR DESCRIPTION
**Pull request by adamchester**
Warning this PR is set to merge into staging-2.0

### CODE REVIEW

**Comment by adamchester** [comment]
This also fixes #777

**Comment by merbla** [comment]
@adamchester is preview2 the toolset version that will align with Core RTM?  Thinking we should hang out for the 27th and see what the go live tooling is.

**Comment by adamchester** [comment]
I believe it is the RTM, but yeah, anything could happen in next few days.

http://netlandingpage-rtm.azurewebsites.net/net/download

**Comment by adamchester** [comment]
The only risk is bumping the SDK version number again.

**Comment by nblumhardt** [comment]
:+1: should move us close to, if not perfectly in line with, what we need for RTM. Thanks Adam!

**Pull request merged**
