### PR TITLE
Independent Build for Perf Tests.

### PR DESCRIPTION
**Pull request by merbla**
Looking to setup an AppVeyor Build for Perf Tests here - https://ci.appveyor.com/project/serilog/serilog-jaske

### CODE REVIEW

**Comment by nblumhardt** [comment]
Great idea; doesn't look like it's running the perf tests though, AFAICT from the output. Will we be able to do a perf run (even a limited one?) without timing out AppVeyor?

**Comment by merbla** [comment]
This is the output.  Correct we may timeout, just wanted to try a few tweaks.

https://ci.appveyor.com/project/serilog/serilog-jaske/build/5

**Comment by nblumhardt** [comment]
Thanks, not sure what I was looking at :-) ... merge ahoy!

**Comment by merbla** [comment]
@nblumhardt I was thinking we can try to reduce the TFM running in the tests.  Are #IF defs significant enough across runtimes to warrant running on all targets?

**Comment by nblumhardt** [comment]
I think it should only be running the latest .NET Core and .NET Framework (I could be wrong). Limiting the TFMs sounds good.

Looks like the results show the same problem running .NET Core benchmarks as I'm hitting locally:

https://ci.appveyor.com/project/serilog/serilog-jaske/build/5#L8703

```
// *** Execute ***
// Launch: 1 / 1
// Execute: C:\Users\appveyor\AppData\Local\Temp\1\3aa7825e-c71b-41da-8ecd-32f9fe3286c1\3aa7825e-c71b-41da-8ecd-32f9fe3286c1\assembly\dl3\4a80e9bf\61527e43_24dcd201\BDN.Generated.exe 
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'BenchmarkDotNet.Core, Version=0.10.3.0, Culture=neutral, PublicKeyToken=aa0ca2f9092cefc4' or one of its dependencies. The system cannot find the file specified.
   at BenchmarkDotNet.Autogenerated.Runnable.Run(Boolean isDiagnoserAttached)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.Program.Main(String[] args)
ExitCode != 0
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!
// ***** BenchmarkRunner: Finish  *****
```

I might try a BDN update to see if anything's changed.

**Comment by skomis-mm** [comment]
@nblumhardt , try [this](https://github.com/serilog/serilog-sinks-periodicbatching/blob/dev/test/Serilog.Sinks.PeriodicBatching.PerformanceTests/xunit.runner.json). Will solve running on the full framework.

**Pull request merged**
