### PR TITLE
Changed to use branch specific badges

### PR DESCRIPTION
**Pull request by merbla**
Updating read me to get ready for build/nuget badges for pre-release.  (v2 etc)

### CODE REVIEW

**Comment by nblumhardt** [comment]
Hey mate, what do you think about just updating the badge to point to master only? Not sure we're ready enough on the v2 branch to make publicising its status worthwhile, I'm still on the fence about a lot of it :-) ...?

**Comment by merbla** [comment]
Do you think dev is worthwhile (along with master)?  Thinking of people quickly seeing the PR status of something recently moved to dev.  Also was thinking on how we would go about surfacing the dev NuGet package.

**Comment by nblumhardt** [comment]
LGTM mate.

RE the dev package, perhaps we should sort out that MyGet feed; will dig up the last thread on it... :+1:

**Comment by nblumhardt** [comment]
After merging, looked a bit funny not having the summary of the repo purpose ahead of the table, so gave it a slight tweak on the way in (couldn't resist :-))

**Comment by merbla** [comment]
+1 for style :satisfied:

**Comment by merbla** [comment]
Was looking at MyGet, now trying understand the benefit of using that vs alpha/beta NuGet from AppVeyor on dev branch.

Thoughts??

**Comment by nblumhardt** [comment]
AppVeyor's definitely a welcome simplification if we can make it work, +1 there

**Pull request merged**
