### PR TITLE
Enable AoT and trimming analyzers

### PR DESCRIPTION
**Pull request by martincostello**
- Enable AoT and trim analyzers for `net6.0` and above.
- Fix trim warnings identified by analyzers.

Contributes to #1985.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Sorry about the silence on this! I checked in when it was still WIP and didn't realise that you'd fixed the build issue.

Did you reach any new conclusions about how the public Serilog API might evolve to better support trimming?

Happy merging this once `dev` is 4.0.0 (#2015) and working forward from there.

**Comment by martincostello** [comment]
> Did you reach any new conclusions about how the public Serilog API might evolve to better support trimming?

I didn't think about it much - once I reached a public interface I stopped digging much further as it would have lead to breaking changes to be able to pass a generic type through with all the right annotations for things like destructuring properties etc.

I'd be happy to help contribute towards a solution with you folks separately back in #1985.

**Comment by nblumhardt** [comment]
Hi @martincostello; there was some progress on this in https://github.com/serilog/serilog/pull/2027, do those changes overlap substantially with this PR? (Guessing yes?)

**Comment by martincostello** [comment]
Looks like it did everything except enable the analysers: https://github.com/serilog/serilog/pull/2008/files#diff-e2a968c34d16c6dc034a40eaf9cc66d86a8d07662cd059cc895eb6b4149f143a

**Pull request closed without merging**
