### PR TITLE
3.0.0 Release

### LINKED ISSUE #1464: Repeated placeholders within a message template cause selfLog to incorrectly log a message
**Description**
When passing a placeholder into a message template more than once, it updates a sink correctly but selfLog writes the line 'Positional property count does not match parameter count'.

**Reproduction**
Log.Information("{0}, {0}", "hello");

PropertyBinder.ConstructPositionalProperties() (line 62) compares the number of placeholders to the number of values provided to populate them.
In this case there is a repeated placeholder so it's comparing 2 and 1, resulting in the update to selfLog.

**Expected behavior**
Compare number of unique placeholders with provided values.

**Relevant package, tooling and runtime versions**
v2.9.0
(netCore 3.0)

**Additional context**

### LINKED ISSUE #1684: Add LogEventLevel.None to mirror Microsoft.Extensions.Logging.LogLevel.None.
**Is your feature request related to a problem? Please describe.**
I have an problem where I want serilog to log only logs from a specific provider and not any other ones.

**Describe the solution you'd like**
The solution would be to add ``None`` to ``LogEventLevel`` to disable a specific source (e.g category as known in Microsoft.Extensions.Logging).

**Describe alternatives you've considered**
I tried to disable them like so:

```cs
await Host.CreateDefaultBuilder()
    .UseContentRoot(Path.GetDirectoryName(executingAssembly.Location)!)
    .ConfigureLogging(logging => logging
        .AddFilter("Default", LogLevel.None))
        // .AddFilter("Remora.Discord.*", LogLevel.Warning))
        // .AddFilter("Microsoft.EntityFrameworkCore.*", LogLevel.None)
        // .AddFilter("Microsoft.Hosting.Lifetime", LogLevel.None)
        // .AddFilter("System.Net.Http.HttpClient.*.LogicalHandler", LogLevel.None)
        // .AddFilter("System.Net.Http.HttpClient.*.ClientHandler", LogLevel.None))
    .UseSerilog((hostingContext, services, loggerConfiguration) => loggerConfiguration
        // .ReadFrom.Configuration(hostingContext.Configuration)
        .MinimumLevel.Override("Remora.*", LogEventLevel.Warning)
        .Enrich.FromLogContext()
        .WriteTo.File(
            DiscordBotSingleton.GetDiscordLogFileName()))
    .ConfigureServices((hostContext, collection) =>
        DiscordBotSingleton.ConfigureServices(hostContext, collection)
            .AddHostedService<ConsoleHostedService>())
    .RunConsoleAsync();
```

where my attempt with to use ``.ConfigureLogging()``. to add a filter to disable them, but use serilog to override the ``Remora.*`` categories to ``LogEventLevel.Warning``.

**Additional context**

Not available at the moment.

### PR DESCRIPTION
**Pull request by nblumhardt**
## What's new in 3.0.0?

**Target framework changes** - Serilog no longer targets `netstandard1.x` or .NET Framework versions earlier than .NET 4.6.2. Users on affected frameworks should continue to target Serilog 2.12.x.

**Removed obsolete APIs** - Many deprecated/obsolete types and functions have been removed. Notably, `JsonFormatter` can no longer be subclassed (either port to `JsonValueFormatter`, use _Serilog.Expressions_, or copy [the original `JsonFormatter` code](https://github.com/serilog/serilog/blob/4d13be50c03e14b6072043799dc7e5dbe4139a19/src/Serilog/Formatting/Json/JsonFormatter.cs) into your project).

**Added APIs** - `LevelAlias.Off` is now provided as an equivalent to _Microsoft.Extensions.Logging_'s `LogLevel.Off`; `Destructure.AsDictionary<T>()` can now be used to mark dictionary types.

**Fewer allocations on many hot paths** - A lot of work has gone into avoiding heap allocations wherever possible.

## Changes

* Change exception message by @sungam3r in https://github.com/serilog/serilog/pull/1762
* Avoided `IEnumerator` allocation (#1769) by @igor84 in https://github.com/serilog/serilog/pull/1770
* Avoid iterator allocations when working with SequenceValue by @sungam3r in https://github.com/serilog/serilog/pull/1785
* Add API approval test by @sungam3r in https://github.com/serilog/serilog/pull/1783
* Bump Newtonsoft.Json from 13.0.1 to 13.0.2 in /test/Serilog.Tests by @dependabot in https://github.com/serilog/serilog/pull/1787
* Introduce `ScalarValue.Null` by @sungam3r in https://github.com/serilog/serilog/pull/1774
* `Tokens` -> `TokenArray` by @sungam3r in https://github.com/serilog/serilog/pull/1778
* Drop `netstandard1.3` and `netstandard1.0` support by @SimonCropp in https://github.com/serilog/serilog/pull/1807
* Remove `JsonFormatter.Escape` by @SimonCropp in https://github.com/serilog/serilog/pull/1804
* Use `WriteLine(char)` by @SimonCropp in https://github.com/serilog/serilog/pull/1803
* Remove extension of `JsonFormatter` by subclassing by @SimonCropp in https://github.com/serilog/serilog/pull/1801
* Remove redundant overrides from `LoggerSinkConfiguration` by @SimonCropp in https://github.com/serilog/serilog/pull/1800
* Avoid `StringWriter.ToString()` calls by @sungam3r in https://github.com/serilog/serilog/pull/1782
* Remove the obsolete `RawFormatter` type by @nblumhardt in https://github.com/serilog/serilog/pull/1808
* .NET 7 SDK by @SimonCropp in https://github.com/serilog/serilog/pull/1806
* Remove `OutputProperties.GetOutputProperties()` by @SimonCropp in https://github.com/serilog/serilog/pull/1805
* Verify API by @SimonCropp in https://github.com/serilog/serilog/pull/1809
* Remove redundant nullable suppressions by @SimonCropp in https://github.com/serilog/serilog/pull/1810
* Remove duplicate `Where()` calls in `FindConfigurationMethods()` by @SimonCropp in https://github.com/serilog/serilog/pull/1812
* Remove `net45` support by @SimonCropp in https://github.com/serilog/serilog/pull/1811
* Remove redundant `GetTypeInfo()` in `LoadConfigurationAssemblies` by @SimonCropp in https://github.com/serilog/serilog/pull/1817
* Remove `GetTypeInfo()` from `FindConfigurationMethods(()` by @SimonCropp in https://github.com/serilog/serilog/pull/1815
* Remove redundant `GetTypeInfo()` in `EnumScalarConversionPolicy` by @SimonCropp in https://github.com/serilog/serilog/pull/1816
* Remove obsolete `PropertyToken` constructor by @SimonCropp in https://github.com/serilog/serilog/pull/1819
* `switch` expressions by @SimonCropp in https://github.com/serilog/serilog/pull/1818
* Do not allocate strings for `TextWriter.Write()` by @sungam3r in https://github.com/serilog/serilog/pull/1775
* Simplify reflection in` SettingValueConversions` by @SimonCropp in https://github.com/serilog/serilog/pull/1814
* Improve `GetPropertiesRecursive()` performance by @SimonCropp in https://github.com/serilog/serilog/pull/1813
* Use `Convert.ToHexString()` in `ByteArrayScalarConversionPolicy()` by @sungam3r in https://github.com/serilog/serilog/pull/1776
* Remove `FEATURE_ASYNCLOCAL` by @SimonCropp in https://github.com/serilog/serilog/pull/1822
* Remove `FEATURE_HASHTABLE` by @SimonCropp in https://github.com/serilog/serilog/pull/1823
* Use `IsEnum` for enum check in `EnumScalarConversionPolicy` by @SimonCropp in https://github.com/serilog/serilog/pull/1825
* Comments on `Hashtable` use in `MessageTemplateCache` by @SimonCropp in https://github.com/serilog/serilog/pull/1828
* Remove `GetTypeInfo()` from `PropertyValueConverter` by @SimonCropp in https://github.com/serilog/serilog/pull/1824
* Avoid repeated `GetType()` in `PropertyValueConverter` by @SimonCropp in https://github.com/serilog/serilog/pull/1832
* Leverage dictionary `TryAdd()` and items constructor by @SimonCropp in https://github.com/serilog/serilog/pull/1830
* Use array instead of list when we know the size in `PropertyValueConverter` by @SimonCropp in https://github.com/serilog/serilog/pull/1831
* Move `net46` target to `net461` by @SimonCropp in https://github.com/serilog/serilog/pull/1827
* Clean up `JsonValueFormatter` by @SimonCropp in https://github.com/serilog/serilog/pull/1835
* `var` in `JsonFormatter` by @SimonCropp in https://github.com/serilog/serilog/pull/1838
* Remove obsolete `SelfLog.Out` by @SimonCropp in https://github.com/serilog/serilog/pull/1837
* Remove obsolete `JsonFormatter` `omitEnclosingObject` overload by @SimonCropp in https://github.com/serilog/serilog/pull/1834
* Remove obsolete `PushProperties()` by @SimonCropp in https://github.com/serilog/serilog/pull/1836
* No point putting `_minimumLevel` and `_levelSwitch` on stack by @SimonCropp in https://github.com/serilog/serilog/pull/1840
* Avoid casting enum to `int` where possible by @SimonCropp in https://github.com/serilog/serilog/pull/1841
* Leverage nullable char in `JsonFormatter` by @SimonCropp in https://github.com/serilog/serilog/pull/1839
* Use correct overload with `char` in `JsonFormatter` by @sungam3r in https://github.com/serilog/serilog/pull/1842
* Annotate Serilog for trimming by @agocke in https://github.com/serilog/serilog/pull/1690
* Fix `net471` `DisableImplicitFrameworkReferences` by @SimonCropp in https://github.com/serilog/serilog/pull/1846
* Fix 461 `TargetFramework` constants in tests by @SimonCropp in https://github.com/serilog/serilog/pull/1847
* Missing API approval by @SimonCropp in https://github.com/serilog/serilog/pull/1848
* `net471` supports `ITuple` by @SimonCropp in https://github.com/serilog/serilog/pull/1849
* Remove `FEATURE_GETCURRENTMETHOD` const by @SimonCropp in https://github.com/serilog/serilog/pull/1851
* macOS CI by @SimonCropp in https://github.com/serilog/serilog/pull/1858
* Run tests on mac by @SimonCropp in https://github.com/serilog/serilog/pull/1860
* BenchmarkDotNet 0.13.5 by @SimonCropp in https://github.com/serilog/serilog/pull/1861
* Cache empty text token by @SimonCropp in https://github.com/serilog/serilog/pull/1859
* Simplify `PublicApi_Should_Not_Change_Unintentionally()` test by @SimonCropp in https://github.com/serilog/serilog/pull/1864
* Move from `net461` to `net462` by @SimonCropp in https://github.com/serilog/serilog/pull/1863
* Remove redundant `GetPackagingOutputs` by @SimonCropp in https://github.com/serilog/serilog/pull/1867
* Use char delimiters by @SimonCropp in https://github.com/serilog/serilog/pull/1868
* Remove redundant reference assemblies by @SimonCropp in https://github.com/serilog/serilog/pull/1866
* Introduce PolySharp by @sungam3r in https://github.com/serilog/serilog/pull/1845
* Missing PolySharp changes by @SimonCropp in https://github.com/serilog/serilog/pull/1869
* Simplify build scripts by @SimonCropp in https://github.com/serilog/serilog/pull/1865
* Added `ReusableStringWriter` by @igor84 in https://github.com/serilog/serilog/pull/1771
* PublicApiGenerator v11 by @SimonCropp in https://github.com/serilog/serilog/pull/1877
* Use `langword` in XML comments by @sungam3r in https://github.com/serilog/serilog/pull/1871
* Avoid creating `SafeAggregateSink` wrapper around empty list by @sungam3r in https://github.com/serilog/serilog/pull/1878
* Remove obsolete classes by @sungam3r in https://github.com/serilog/serilog/pull/1874
* Add space settings by @sungam3r in https://github.com/serilog/serilog/pull/1885
* Make `Alignment` and `LevelOverrides` readonly by @sungam3r in https://github.com/serilog/serilog/pull/1884
* Remove redundant `CallerArgumentExpressionAttribute` by @SimonCropp in https://github.com/serilog/serilog/pull/1886
* Remove `MessageTemplateToken.StartIndex` by @SimonCropp in https://github.com/serilog/serilog/pull/1882
* Microsoft.NET.Test.Sdk 17.5.0 by @SimonCropp in https://github.com/serilog/serilog/pull/1862
* Throw, rather than exit, when any command in the build script fails by @nblumhardt in https://github.com/serilog/serilog/pull/1887
* Suppress some warnings, tidy up some namespacing by @nblumhardt in https://github.com/serilog/serilog/pull/1888
* Reinstate `LoggerSinkConfiguration.Sink(ILogEventSink, LogEventLevel)` by @nblumhardt in https://github.com/serilog/serilog/pull/1889
* Avoid some alloc with `Array.Empty` by @SimonCropp in https://github.com/serilog/serilog/pull/1898
* Destructure `ReadOnlyDictionary` as `Dictionary` by @sungam3r in https://github.com/serilog/serilog/pull/1897
* Remove redundant `IDictionary` cast by @SimonCropp in https://github.com/serilog/serilog/pull/1900
* Adding ability to dispose nested loggers in `WriteTo.Logger()` by @srogovtsev in https://github.com/serilog/serilog/pull/1890
* Optimize `AddPropertyIfAbsent` by @sungam3r in https://github.com/serilog/serilog/pull/1872
* Accept/pass through the standard `levelSwitch` option in `WriteTo.Logger()` by @nblumhardt in https://github.com/serilog/serilog/pull/1902
* Add `net47` target by @SimonCropp in https://github.com/serilog/serilog/pull/1905
* Annotate `WithProperty()` by @sungam3r in https://github.com/serilog/serilog/pull/1907
* Add `LoggingLevelSwitch.MinimumLevelChanged` by @sungam3r in https://github.com/serilog/serilog/pull/1908
* Fix #1464, don't log parameter count mismatch message incorrectly by @nblumhardt in https://github.com/serilog/serilog/pull/1903
* Add `Destructure.AsDictionary<T>()` by @sungam3r in https://github.com/serilog/serilog/pull/1906
* Add `LevelAlias.Off`; fixes #1684 by @nblumhardt in https://github.com/serilog/serilog/pull/1910
* Use `JsonValueFormatter` to implement classic `JsonFormatter` by @nblumhardt in https://github.com/serilog/serilog/pull/1911
* Include `README.md` in the NuGet package for display on nuget.org by @nblumhardt in https://github.com/serilog/serilog/pull/1916

### CODE REVIEW

**Comment by nblumhardt** [comment]
Folks, I think it's time to set a date for this - anything that misses out can always land in a 3.x, or a 4.x down the track.

I'll spend some time running over the last few changes/PRs this week.

Unless there's a better date, let's aim for **June 21st** (one month from today). :-)

**Comment by nblumhardt** [comment]
While it's not as tight as automating tests across the ecosystem, I have now tested the `3.0.0-dev-02018` prerelease with the first ten NuGet search results for "serilog sink" that are not directly maintained within the Serilog org:

```xml
      <PackageReference Include="sentry.serilog" Version="3.33.0" />
      <PackageReference Include="serilog.sinks.applicationinsights" Version="4.0.0" />
      <PackageReference Include="serilog.sinks.awscloudwatch" Version="4.0.171" />
      <PackageReference Include="serilog.sinks.datadog.logs" Version="0.5.2" />
      <PackageReference Include="serilog.sinks.elasticsearch" Version="9.0.1" />
      <PackageReference Include="serilog.sinks.graylog" Version="2.3.0" />
      <PackageReference Include="serilog.sinks.loggly" Version="5.4.0" />
      <PackageReference Include="serilog.sinks.mongodb" Version="5.3.1" />
      <PackageReference Include="serilog.sinks.mssqlserver" Version="6.3.0" />
      <PackageReference Include="serilog.sinks.seq" Version="5.2.2" />
      <PackageReference Include="serilog.sinks.splunk" Version="3.7.0" />
```

I only tested AWS CloudWatch as far as failing to configure the sink (I don't have an AWS CloudWatch configuration set up), and the others I tested as far as failing to emit an event (no receiving endpoints). None appeared to be broken by the API removals in 3.0.0.

I dug into a few more packages that seemed interesting from further down the list. All look fine for Serilog 3.

Given that we have the option to back out any removals that end up causing pain, I think it's safe enough to ✔️  the sink ecosystem work item.

**Comment by sungam3r** [comment]
Good. It was expected, at least by me.

**Comment by nblumhardt** [comment]
Aiming to press the button on this in ~24 hours or so :-)

**Pull request merged**
