### PR TITLE
Enable .NET Native on AppVeyor + workaround on compiler error for #993

### PR DESCRIPTION
**Pull request by skomis-mm**
Basically adds an empty UWP project (SDK = [10.0.10586](https://www.appveyor.com/docs/build-environment/#visual-studio-2017)) to the `test` folder and references `Serilog` to activate .NET Native on build. I didn't include this project to the solution to avoid tooling dependency. For the same reason build script was moved to a separate file. Not sure if its correct though.

### CODE REVIEW

**Comment by skomis-mm** [comment]
First pass reported incorrect `success`, needs some tweaking

**Comment by skomis-mm** [comment]
second pass reported correct [fail](https://ci.appveyor.com/project/serilog/serilog/build/865). Now let's try the workaround for [#993](https://github.com/serilog/serilog/issues/993)

**Comment by nblumhardt** [comment]
LGTM; just one nit - could we call the UWP project _Serilog.UwpTest_, (_UwpTest**s**_?) or, put it under _sample/UwpDemo_? The name jumps out at me as "an implementation of Serilog for UWP", otherwise.

**Comment by skomis-mm** [comment]
- renamed to Serilog.UwpTests to match other project names in that folder
- changed project type to `unit test project` so ideally tests can also be added and run on that runtime (for now its impossible because Visual Studio 2017 image runs on Windows Server 2016 on AppVeyor,)

**Pull request merged**
