### PR TITLE
Fixing up for grabs link.

### PR DESCRIPTION
**Pull request by MorganW09**
**What issue does this PR address?**
#1376 

**Does this PR introduce a breaking change?**
No.

**Other information**:
Markdown file only change.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks for spotting that! The suggested alternative link only covers the one repository, I think the correct one is:

https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+archived%3Afalse+user%3Aserilog+label%3Aup-for-grabs

Does this match your expectations? Cheers!

**Comment by MorganW09** [comment]
Thanks for pointing that out @nblumhardt , I've updated it with the link provided.

**Comment by nblumhardt** [comment]
Looks like I spoke too soon, and there are some limitations on who can view this link. I get a 404 when I'm not logged in. Does it work for you when logged in, or does it require some kind of `serilog` org permissions? Thanks!

**Comment by MorganW09** [comment]
Thanks for the update. I lost track of your previous comment.

**Pull request merged**
