### PR TITLE
Second attempt at initial LogContext support for Core 5.0

### PR DESCRIPTION
**Pull request by colin-young**
For #588 (and incorporates notes from https://github.com/serilog/serilog/pull/640). Apologies for the second submission, but I made a right mess of merging some upstream changes. Fortunately git was able to clean up my mess.

* Removed .Net 4.0 (hoping for #635 )
* Changed from .Net 4.5.1 to 4.5.2, but left 4.5 as-is
* Added ASYNCLOCAL and REMOTING feature pivots
* Removed remoting support from .Net Core
* Replaced CallContext with AsyncLocal<T> when ASYNCLOCAL feature is available

I have not tested in a remoting situation, and have not reviewed the unit tests to see how they are covering that. All unit tests do pass (except maybe `DoesNotPreventCrossDomainCalls` which I haven't run yet).

Looking for some early feedback.

Thanks.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Hi Colin - still not sure the repo is in a good state - some commits in the list above from another PR :-( .... Does the branch just need updating? Let me know if I can help, unfortunately I'm not sure what might cause this.

**Comment by colin-young** [comment]
I'm not sure either. I'll take another crack at it tomorrow. At the time I
just assumed that it must have been a PR merged after I forked, but now
that I think about it that doesn't make sense.

**Comment by khellang** [comment]
@colin-young It's not a good idea to commit to `dev` and send PRs from there. It's too easy to fetch down changes and have them applied to the dev branch. If I were you I'd create a new branch and cherry-pick the commits you'd like to include in the PR and open up a new PR from that branch.

**Comment by colin-young** [comment]
Yeah, I've been doing my work in a branch (we use a feature-branch model at
my day job so that's how I've been trying to do things). I think my mistake
was trying to merge my branch into dev and then trying to send that into a
PR. I did try to rebase on the latest work (there are merge conflicts
otherwise) and I think that's where things went off the rails. Going to
reset again later today and try to get a clean PR.

**Comment by colin-young** [comment]
Okay. I give up. I've got a "clean" commit history that just has my changes, but it won't merge. There are conflicts because I've modified project.json and so has serilog/serilog. There appear to have been have been 2 PRs since I forked from 2a632bab4799cae93620fee7366810405fac44b8

So do I check in with conflicts, or try to fix them? I can't figure out how to fix them without pulling in the intermediate PRs.

**Comment by khellang** [comment]
I'm not really sure what's going on here. Looks like there's a merge commit in there as well. That's probably it.

Just an FYI, you're sending this PR from the dev branch, not the feature branch. The feature branch would've been better. Always keep your dev/master in a clean state.

Here's a runbook to get out of this. Assuming you're on the `dev` branch locally...

 - `git branch <temporary-branch>` - To check check out a new, temporary branch (including the commit you want), this is probably unnecessary, but better safe than sorry :wink:
 - `git reset --hard upstream/dev` - Rewind the dev branch to the upstream state. You might also want to `git fetch upstream` before this, to make sure you have the latest upstream changes.
 - `git push -f origin dev` - Force push to clean up your forked dev branch
 - `git checkout -b <feature-branch>` - Checkout a new feature branch, this is the one you want to send the PR from
 - `git cherry-pick feb0d46d488f203b75dc2b15a3ea7eac88724709` - Pick the single commit you want
 - Fix potential merge conflicts
 - `git push -u origin <feature-branch>` - Push the new feature branch. this should now be up to speed with upstream dev and have the single commit extra
 - Go to the serilog/serilog repo and open a PR from the new branch. The UI will prompt you about the new branch.
 - `git branch -D <temporary-branch>` - Delete the temporary branch

**Comment by khellang** [comment]
If you want to jump on [JabbR](https://jabbr.net/#/rooms/serilog) we can walk though it together :smile:

**Comment by colin-young** [comment]
That's more or less the plan I came up with after I realized I've got all
the code and I can just "start over" fresh, although the cherry pick will
probably make it easier to identify the merge conflicts.

I'm about to get on a flight, so I'll try to get to it later this evening
(I'm on US eastern time so I've still got 6 or 8 hours of the day left).

**Pull request closed without merging**
