### PR TITLE
Serilog EventStore Sink

### PR DESCRIPTION
**Pull request by SeanFarrow**

### CODE REVIEW

**Comment by nblumhardt** [comment]
No, leaving it unsigned is fine if necessary.

RE building, opening a "Developer Command Prompt for VS2014" console window should do it.

You can just run `./Build.ps1 -notouch` to smoke test the build; it'll use 0.0.0 as the version, and won't update any assembly attributes, but if that works then I think it's all good to go.

Cheers!

**Comment by SeanFarrow** [comment]
Hi,

I’ll sort this in the next week or so.
Cheers
Sean.

**Comment by nblumhardt** [comment]
Hi Sean - are you still keen on adding EventStore support? If so, the process has changed somewhat since this PR was opened, we've got all of the sinks out in separate repositories under the `/serilog` organisation and have started accepting new sinks as repository transfers instead of PRs. If you do want to push ahead with this, checking out e.g. https://github.com/serilog/serilog-sinks-mongodb should offer a good example. All the best!

**Comment by SeanFarrow** [comment]
Hi Nick,

Yes, I do want to do this, let me sort the repo out in terms of how it’s structured.
Who do I contact for a transfer? Would I still then be able to commit, or need to fork to contribute?
Cheers
Sean.

**Comment by nblumhardt** [comment]
Hi Sean,

When you are ready to transfer, there's a GitHub function that should let you request a transfer to the `serilog` organisation.

We'll create an "owners" team for the repo so you can continue to contribute/maintain it under the Serilog org without forking etc.

Cheers!
Nick

**Pull request closed without merging**
