### PR TITLE
Update Nuget package license format to new format

### PR DESCRIPTION
**Pull request by tsimbalar**
**What issue does this PR address?**
https://github.com/serilog/serilog/issues/1265

### CODE REVIEW

**Comment by tsimbalar** [comment]
For some reason, the Nuget package generated by https://ci.appveyor.com/project/serilog/serilog/builds/21388982/artifacts does not seem to have the proper licensing information

image


Not sure what to think of this ... it worked fine with *Serilog.Sinks.Console* and *Serilog.Settings.Configuration*.

**Comment by nblumhardt** [comment]
🤔 

This repository does include a `global.json` file that pins the tooling to 2.1, while _Console_ and _Configuration_ don't - perhaps shifting the tooling version forward will do the job?

**Comment by nblumhardt** [comment]
Any thoughts on what we should do with this one, @tsimbalar ?

**Comment by tsimbalar** [comment]
Thanks for the nudge !

Sorry, I haven't been able to do much Serlog work lately 😑.

I'll try to get to it eventually, but if somebody has the time to look into it, go for it !

**Comment by nblumhardt** [comment]
@tsimbalar I'm only just getting some time put aside again, too. Looking forward to digging into some more substantial Serilog features in the next little while, if the calendar stays sane (fingers crossed :-))

I'll take a look if no one else beats me to it.

**Comment by nblumhardt** [comment]
Works now that #1315 has updated the build-time SDK 🎉

**Pull request merged**
