### PR TITLE
2.12.0 Release

### PR DESCRIPTION
**Pull request by nblumhardt**
### Improved and expanded `<Nullable>enable</Nullable>` support

A huge number of commits have gone into completing and refining non-null reference type annotations, which now cover the entire public Serilog API. The Serilog project itself now builds with non-null reference type checking globally enabled :tada: 

### `IAsyncDisposable` support

Sinks that need to flush changes using asynchronous APIs can now implement `IAsyncDisposable` and prevent the possibility of deadlocking while waiting for tasks to complete.

To drive this, `Logger` can now be disposed via `using async`:

```csharp
using async var log = new LoggerConfiguration().CreateLogger();
```

and the `Log` class provides `Log.CloseAndFlushAsync()`:

```csharp
await Log.CloseAndFlushAsync();
```

### `DateOnly` and `TimeOnly` support

The `DateOnly` and `TimeOnly` types introduced in .NET 6 are now correctly handled as scalar values when capturing.

## Merged PRs

 * #1713, #1716, #1715, #1722, #1721, #1720, #1729 - improved non-null reference type annotations (@SimonCropp)
 * #1702 - `DateOnly` and `TimeOnly` support (@SimonCropp)
 * #1764, #1703, #1708, #1709, #1712, #1724, #1730, #1747 - build and dependency updates (@SimonCropp)
 * #1723, #1728, #1731, #1732, #1734, #1735, #1733, #1736, #1739, #1746, #1745, #1741, #1742 - code clean-up and modernization (@SimonCropp)
 * #1750 - `IAsyncDisposable` support for `Logger` and sinks (@nblumhardt)
 * #1699 - fix some XDOC documentation (@sungam3r)
 * #1719 - remove redundant `!` operator from `null` in conditions (@sungam3r)
 * #1725 - introduce file-scoped namespaces (@sungam3r)
 * #1700, #1704, #1707 - more nulllable annotation updates (@nblumhardt)
 * #1711 - fix support for `ValueTuple` (@SimonCropp)

### CODE REVIEW

**Comment by SimonCropp** [comment]
@nblumhardt is this one baked? need help on anything else?

**Comment by nblumhardt** [comment]
@SimonCropp :bread: :+1: 

For the `IAsyncDisposable` changes to be usable, we'll also need https://github.com/serilog/serilog-sinks-periodicbatching/pulls, so it would be great if you have time to take a look.

Some support in _Serilog.Extensions.Logging_ and _.Hosting_ is also going to be required, I'm not sure exactly how much work is involved but I should have a chance to check it out soon, and although it's a big part of the story, we probably shouldn't block on it.

I'll write up some release notes in this ticket now :-)

**Comment by nblumhardt** [comment]
Think we're good to go! :sunglasses:

**Comment by nblumhardt** [comment]
Ooh actually not quite, hold fire :-)

**Comment by nblumhardt** [comment]
https://github.com/serilog/serilog/pull/1751

**Pull request merged**
