### PR TITLE
Capture additional params (named) not in template

### PR DESCRIPTION
**Pull request by adamchester**
See #741 for details.

This addresses #737

### CODE REVIEW

**Comment by adamchester** [comment]
I think this is ready.

**Comment by nblumhardt** [comment]
Back to this! Sorry about the long delay.

Just one nitpicky thought, would the performance impact (on the "correct" case) be reduced from one comparison per argument, to one comparison per call, if we used:

```csharp
var result = new LogEventProperty[messageTemplateParameters.Length];
for (var i = 0; i < matchedRun; ++i)
{
    var property = template.NamedProperties[i];
    var value = messageTemplateParameters[i];
    result[i] = ConstructProperty(property, value);	
}

for (var i = matchedRun; i < messageTemplateParameters.Length; ++i)
{
    var value = _valueConverter.CreatePropertyValue(messageTemplateParameters[i]);
    result[i] = new LogEventProperty("__" + i, value);
}
```

I find it fractionally easier to follow broken into the two loops, but that might not be universal...

Keen to merge this either way, just thought I'd put the variation out there.

**Comment by adamchester** [comment]
Yep, agreed. What you proposed is a slight improvement, and it's done in f3896ba.

**Comment by nblumhardt** [comment]
:tada:

**Pull request merged**
