### PR TITLE
Updated Serilog.Sinks.ApplicationInsights

### LINKED ISSUE #360: Update Azure Application Insights sink to new API
I see that the current ApplicationInsights sink in the serilog repo is for the old version (working for Visual Studio Online) which is now deprecated. The new version works with Azure, and the SDK, etc. are different.

Looking into the PRs, I found that @jbattermann updated the sink to this new version but left it in another repo (to avoid problems with pre-release). 

May I suggest deleting the current ApplicationInsights sink from the Serilog repo, since it's now deprecated, and maybe pull the other repo in or update the documentation to send people to it? Otherwise it's pretty difficult to discover there's a new version for Azure Application Insights unless you look at the closed pull requests or search in NuGet for pre-release packages.

I can send a PR updating the documentation once you confirm if you want to do something with this.

(Please @jbattermann, correct me if I got something wrong!)

### PR DESCRIPTION
**Pull request by jbattermann**
.. to the new Azure Portal based Application insights as discussed & this basically closes #360. For clarity-sake, I've added -pre to the .nuspec version, too.. not sure if you want to keep it that way.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks! Merged to `dev`. Before pushing to master I think we need to sort out versioning; this and the Mongo sink changes recently submitted will each require a major version increment, which `Build.ps1` doesn't handle yet. Creating an issue for it now. Cheers!

**Comment by jbattermann** [comment]
Sure thing Nicholas! I'll take care of future updates (as I use / will use the core one from then on) and send pull requests when / if the AI sink needs updates.

**Comment by nblumhardt** [comment]
@jbattermann all done! And, the Application Insights sink has graduated to its own repository: https://github.com/serilog/serilog-sinks-applicationinsights with its own CI build, publishing to NuGet

**Comment by jbattermann** [comment]
Perfect! Already pushed the very last version of my old / now outdated sink that simply adds [Obsolete] markers to give users an indicator to move back over to the core AI sink & going to unlist it in a couple days.

**Pull request merged**
