### PR TITLE
Improves XML documentation

### PR DESCRIPTION
**Pull request by rafaelsc**
**What issue does this PR address?**
None

**Does this PR introduce a breaking change?**
No.

**Please check if the PR fulfills these requirements**
- [x] The commit follows our [guidelines](https://github.com/serilog/serilog/blob/dev/CONTRIBUTING.md)
- [ ] Unit Tests for the changes have been added (for bug fixes / features)

**Changes:**

 - Small fixes to some XML Documentation
 - Add exception information XML Documentation
 - Code Format - _Better separation of validation and code._
 - Use the same property Name validation code too all code path.

### CODE REVIEW

**Comment by rafaelsc** [comment]
No new unit test is needed.

**Comment by rafaelsc** [comment]
I have more commits to this PR. I will finish in 2hours.

**Comment by rafaelsc** [comment]
Done. All changes are commited

**Comment by nblumhardt** [comment]
Thanks! Will squash and merge as there are a few commits :+1:

**Pull request merged**
