### PR TITLE
.net35 backport

### PR DESCRIPTION
**Pull request by forcewake**
I successfully moved main package and several
* Serilog.Sinks.EventLog
* Serilog.Sinks.Log4Net
* Serilog.Sinks.MSSqlServer

package to the .net35. I know that this is really old framework, but sometimes people should use it :-1: 

The main difference - there is no support for Rx Extensions for .net35. Right now I don't how to save this functionality in the .net35.

### CODE REVIEW

**Comment by nblumhardt** [comment]
I'm happy for us to make this available by some means - .NET 3.5 support is definitely in the realm of "best effort", but I think most users who take that on should be aware/understand the caveats (the "stuck in 2005" enterprise shops aren't jumping on to new structured logging libraries in great numbers :))

Here's what I think we should do:

 * Fork /serilog/serilog to /serilog/serilog-net35 and add @forcewake and @ashleydavis as owners (if willing)
 * @forcewake and @ashleydavis can merge in the changes to support .NET 3.5
 * Create an _AppVeyor_ build config for it, publishing to NuGet as `Serilog-net35`
 * Accept issues via the Serilog tracker, but pass on these where it's not a simple fix/PR
 * Owners of the .NET 3.5 repo can backport new features etc. as desired, but this wouldn't happen by default for new work

I.e. we put it out there and see how it goes :)

Not back-porting new features will ease the maintenance load. It also makes a good case-study in process for how we might be able to deprecate .NET 4.0 support when the time comes for that.

Thoughts?

**Comment by ashleydavis** [comment]
I'm happy to help in anyway that I can.

**Comment by nblumhardt** [comment]
Due to https://help.github.com/articles/duplicating-a-repository/ this needs to be set up from scratch. There's a bare repo at https://github.com/serilog/serilog-net35 which I'll init and set up ownership for shortly.

**Comment by forcewake** [comment]
@nblumhardt Great! Thank you for your time, I and @ashleydavis will push our changes to this repository as soon as possible

**Comment by SeanHSynect** [comment]
@ashleydavis Did you ever complete your implementation of Serilog for Unity3D? I was trying to implement it myself, but realized you said you had your own implementation for it. I really was hoping for Serilog for .NET 3.5, but it seems this thread died and the link to the net3.5 Serilog is empty.

**Comment by ashleydavis** [comment]
Yeah I simply built the .Net 3.5 version to a dll and I now use that in Unity builds. It works well on both PC and Android. You have to drag across some dependency dlls.

I've never felt the need to make changes to it.

Things are changing in the .NET world.

- Xamarin was bought by MS and is now free.
- Mono is now MIT licenced.
- .NET itself is open sourced.
- MS and Unity are working together (Unity and VS work well together).
- Unity has joined the .NET foundation.

Hopefully all this means that Unity will get there act together and make the latest version of .NET available!

**Comment by SeanHSynect** [comment]
@ashleydavis Pardon my confusion, but where can we find the .Net 3.5 version? 

The repo here: https://github.com/serilog/serilog-net35 seems to be empty.

**Comment by ashleydavis** [comment]
Check out my fork: https://github.com/ashleydavis/serilog

I just moved it back to my repo list, in case you were having trouble finding it before.

**Comment by SeanHSynect** [comment]
@ashleydavis It seems as though that fork has .Net 4.0. Am I incorrect in this observation?

**Comment by ashleydavis** [comment]
Sorry, forgot to mention that you'll specifically need to checkout the  .NET 3.5 branch:

https://github.com/ashleydavis/serilog/tree/feature-net35-backport

**Comment by ashleydavis** [comment]
Note that my fork could be out of date. But it should at least work with Unity as that's where I have compiled my dlls from. Let me know if you have problems and I can help.

**Comment by SeanHSynect** [comment]
I don't suppose anyone wrote a 3.5 backport for the [Serilog SeqSink](https://github.com/serilog/serilog-sinks-seq) did they?

**Comment by nblumhardt** [comment]
@SeanHSynect I think porting to `WebClient` is the way to go; it shouldn't be a huge amount of work but it's hard to get it to the top of the backlog here. If you decide to hack it out I'd be happy to help debug etc.! :-)

**Comment by ashleydavis** [comment]
We ended up rolling out own HTTP log collector and viewer for use with Unity apps.

Here's an example of how to output logs via HTTP from Unity: [https://github.com/Real-Serious-Games/RSG.UnityApp/blob/master/SerilogHttpSink.cs](https://github.com/Real-Serious-Games/RSG.UnityApp/blob/master/SerilogHttpSink.cs)

This is a simple Node.js server that receives those logs via HTTP and stores them in a MongoDB: [https://github.com/Real-Serious-Games/LogServer](https://github.com/Real-Serious-Games/LogServer)

And here is a simple Node.js log-viewer web app that allows you to look at the logs you have stored in MongoDB: [https://github.com/Real-Serious-Games/LogViewer](https://github.com/Real-Serious-Games/LogViewer)

**Comment by SeanHSynect** [comment]
I was able to write my own Unity Seq Sink, but the one think I didn't have control over was dynamic level switching with the backport to .Net 3.5. 

Do you have any idea how to do the equivalent of using LoggingLevelSwitch like in this [article](http://nblumhardt.com/2014/10/dynamically-changing-the-serilog-level/)?

**Comment by ashleydavis** [comment]
So LoggingLevelSwitch doesn't exist in the .Net 3.5 port? 

It could be integrated in, or the .Net 3.5 port could be bought up to date, but you'd be hard pressed to find someone who wants to do that. I wish I had the time but I don't.

I am hoping that Unity will update to the latest .Net sometime in the not too distance future, then we could just start using the latest Serilog ;)

**Pull request closed without merging**
