### PR TITLE
Release 2.7.1

### PR DESCRIPTION
**Pull request by nblumhardt**
* #1075 - overload of `LoggerSinkConfiguration.Wrap()` accepting `LoggingLevelSwitch`
 * #1083 - update package metadata, including `https://` project and icon URLs
 * #1091 - make `{Properties:j}` work consistently with the console sink
 * #1110 - expose an efficient `Logger.None`
 * #1113 - (tooling) improve tests for `LogContext`
 * #1136 - (tooling) fix `build.sh` exit code
 * #1141 - fix logging of `byte[]` smaller than 1 KB
 * #1157 - (tooling) update _.gitignore_
 * #1158 - (tooling) re-enable macOS builds
 * #1163 - SourceLink v2 support
 * #1165 - fix a number of issues with `LoggerSinkConfiguration.Wrap()` affecting `WriteTo.Async()`
 * #1134 - (tooling) add README badges for downloads/stats
 * #1166 - allow `LoggerConfiguration` to be garbage collected after logger is created
 * #1160 - (tooling) update NuGet.org API key
 * (tooling) Update to use the latest .NET SDK

### CODE REVIEW

**Comment by tsimbalar** [comment]
I'm not sure why, but the current pre-release (dev) nuget packages are versioned v2.7.1 ... so I guess this release should be v2.7.1, to avoid going through decreasing versions ?

**Comment by adamchester** [comment]
Why isn't the Travis build status part of the github checks here?

**Comment by nblumhardt** [comment]
I've updated the release notes above and think we've got enough here to warrant merging/moving forward.

Has anyone had an opportunity to put 2.7-dev through its paces in a more demanding setting? I should have some time in the next few days to update various apps, but it'd be great if more people can smoke test, too.

**Comment by tinytech-delivery** [comment]
LGTM, as noted I guess this will be `2.7.1.x`

**Comment by merbla** [comment]
LGTM, as noted it will be `2.7.1` and with existing packages on [NuGet](https://www.nuget.org/packages/Serilog/) not sure it is worth bumping it back.

**Comment by nblumhardt** [comment]
This is now published! 🎉 

One small caveat encountered while updating _Serilog.Sinks.Async_ post-publishing, the implicit reference to `NETStandard.Library` that's now used for the .NET Standard targets implicitly bumps the versions of framework dependencies up. The change will fix DLL hell for some, and require others to upgrade or explicitly specify dependency versions. The world we live in...

Binary compatibility is not impacted, and neither are .NET Framework builds, so fingers crossed this'll all come out fine 😅 .

**Comment by tsimbalar** [comment]
Updated in https://github.com/tsimbalar/serilog-settings-comparison , all tests are green (not that I expected otherwise :P ).

**Comment by tsimbalar** [comment]
Also, it turns out this release was [**build number 999**](https://ci.appveyor.com/project/serilog/serilog/build/999) for AppVeyor ... I hope the next build will not break everything *à la* Y2K bug :)

**Pull request merged**
