### PR TITLE
Removed obsolete VS2015 solution artifacts

### PR DESCRIPTION
**Pull request by nblumhardt**
The DNX work is proceeding in `dev-v2` - these files are remnants of the first attempt that have mislead a few folks.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Review/merge appreciated @serilog/core :-)

**Comment by khellang** [comment]
:+1:

**Comment by merbla** [comment]
Still getting up to speed with dnx however looks good.

**Comment by merbla** [comment]
@khellang is just too quick :open_mouth:

**Pull request merged**
