### PR TITLE
Corrected Example in MessageTemplateFormatMethod documentation comments

### PR DESCRIPTION
**Pull request by JinsPeter**
The example in the documentation was using a wrong name for the attribute. Corrected the usage in the example

### CODE REVIEW

**Review by skomis-mm — APPROVED** [review]
LGTM 👍

**Review by augustoproiete — APPROVED** [review]
LGTM

**Comment by JinsPeter** [comment]
Thanks. So, Is there anything pending from my side to get this merged?

**Comment by augustoproiete** [comment]
@JinsPeter No, you're good. Just giving folks time to 👀

**Comment by JinsPeter** [comment]
Oh.. Okay. Thanks.

**Pull request merged**
