### PR TITLE
size rolling log file

### PR DESCRIPTION
**Pull request by thinktainer**
## This is a sketch of how i'd imagine the new behaviour to work.

- Only size rolling implemented, saving size + date for later, as I feel there needs to be more discussion about desired behaviour
- Doesn't yet follow your advice of factoring this out into a module, at which point the integration points would obviously need to change.

### CODE REVIEW

**Comment by thinktainer** [comment]
I'm submitting this in the current state in order to hopefully get some feedback about implementation / test coverage, design. I hope I'm not too far off the mark, but want to avoid going on a tangent for too long.

**Comment by nblumhardt** [comment]
Thanks for posting this, it looks like you've taken it a long way towards a solid implementation!

As mentioned in https://github.com/serilog/serilog/issues/428, I think this is a difficult one for us to take in the integrated form- there are a few breaking API (e.g. `class RollingFileSink` renamed)  and behavioural changes (must choose a maximum days retention) that would make this possible only with a major revision, and given the very wide usage of the sink it's uncertain whether we'd want to roll any significant change out without a lot of interest.

What do you think of the separate package option? It would essentially be a clean slate, which might also allow for some improvements in how the sink operates and is factored. We've started pushing more in this direction across the board, e.g. just recently we published a new colored console that's achieved a good number of downloads in its 20 days of existence: http://www.nuget.org/packages/serilog.sinks.literate

Cheers!
Nick

**Comment by thinktainer** [comment]
I'd be totally up for that, would you be happy to set up the infrastructure required?

**Comment by nblumhardt** [comment]
Yes, though the process for this currently is for you to set up and do the work in a repository of your own, then transfer ownership of the repo to `serilog` (and join it's "owners" team there).

Probably good to get some thoughts in from @serilog/core in case I'm out on a limb - folks, is this the best way for us all to go about providing a more sophisticated rolling file sink (e.g. with size rolling policies)?

**Comment by merbla** [comment]
If there is nothing common or reusable in the policies I would say *YAS* (Yet Another Sink).  Perhaps `2.0` is the time for this sort of change to the core.

**Pull request closed without merging**
