### PR TITLE
Added support for multiple sinks from the same type just by differentiating them by name

### PR DESCRIPTION
**Pull request by eallegretta**
For instance

    <add key="serilog:write-to:Fatal:RollingFile.pathFormat" value="Logs\{Date}-Fatal.log" />
    <add key="serilog:write-to:Fatal:RollingFile.restrictedToMinimumLevel" value="Fatal" />
    <add key="serilog:write-to:Fatal:RollingFile.outputTemplate" value="{Timestamp:yyyy-MM-dd HH:mm:ss} - {Exception}{NewLine}" />

    <add key="serilog:write-to:Simple:RollingFile.pathFormat" value="Logs\{Date}-Simple.log" />
    <add key="serilog:write-to:Simple:RollingFile.restrictedToMinimumLevel" value="Information" />
    <add key="serilog:write-to:Simple:RollingFile.outputTemplate" value="{Timestamp:yyyy-MM-dd HH:mm:ss} - [{Level}] - {Version} - {Message} - {Exception}{NewLine}" />

    <add key="serilog:write-to:Detailed:RollingFile.pathFormat" value="Logs\{Date}-Detailed.log" />
    <add key="serilog:write-to:Detailed:RollingFile.restrictedToMinimumLevel" value="Verbose" />
    <add key="serilog:write-to:Detailed:RollingFile.outputTemplate" value="{Timestamp:yyyy-MM-dd HH:mm:ss} - [{Level}] - {Message}{NewLine}{Exception}" />

### CODE REVIEW

**Comment by nblumhardt** [comment]
Now that `<appSettings>` support has [moved into the core](http://nblumhardt.com/2015/04/monster-serilog-update-april-2015/) it'd be great to get a plan finalised for this.

I wonder if we could keep a more C#-y feel to the DSL using indexers to identify specific instances of a sink?

```
<add key="serilog:write-to:RollingFile[Detailed].pathFormat" value="Logs\{Date}-Detailed.log" />
```

The main thing I think this feature needs to overcome is pushing the complexity of the syntax too far; it's already quite tricky to work with so I'd rather not add more capabilities if they're ultimately not going to be discovered by many users.

Any more thoughts on this since we first looked at it? Cheers!

**Comment by eallegretta** [comment]
We can certainly change the format the PR was easy to do since I was relying on all the existing magic you have on the code, this will probably require a small change on the regex but I think its doable, I need to update my fork

**Comment by andrewcupper** [comment]
How about something more succinct like this:
``` xml
<add key="serilog:write-to:Simple" value="RollingFile" />
<add key="serilog:write-to:Simple.pathFormat" value="Logs\{Date}-Simple.log" />
<add key="serilog:write-to:Simple.restrictedToMinimumLevel" value="Information" />
<add key="serilog:write-to:Simple.outputTemplate" value="{Timestamp:yyyy-MM-dd HH:mm:ss} - [{Level}] - {Version} - {Message} - {Exception}{NewLine}" />
```

**Comment by nblumhardt** [comment]
Hi all; the target project no longer lives in this repo (at https://github.com/serilog/serilog-settings-appsettings) so need to close this. If you can move to `appsettings.json` (.NET Core) the multiple-sink problem is solved in there, it'd be interesting to hear any feedback on that lib if you can give it a try.

Thanks @eallegretta for putting this forward, sorry it didn't land but if you still have an interest in this perhaps we could hash out a design under a ticket in the new repo? All the best, anyway!

**Pull request closed without merging**
