### PR TITLE
Exclude large strings from the internal message template cache (fixes 523)

### LINKED ISSUE #523: Limit the size of items that the internal message template cache holds
Though the cache itself is limited to 1000 items (https://github.com/serilog/serilog/blob/dev/src/Serilog/Core/Pipeline/MessageTemplateCache.cs#L21) it doesn't behave well in this case:

```csharp
Log.Information(someVeryLargeString);
```

See: https://twitter.com/chraas/status/639783365860851712

Limiting the size of cached templates to a certain initial string length (140 chars?!) will further control growth.

### PR DESCRIPTION
**Pull request by nblumhardt**
Also changes the cache overflow policy to simply reset, hopefully keeping relevant items in the cache when it's outgrown via some misbehaving code.

Fixes #523.

### CODE REVIEW

**Comment by nblumhardt** [comment]
Ping @serilog/core

**Comment by merbla** [comment]
:moneybag:

**Comment by merbla** [comment]
@nblumhardt merging to `master` soon?

**Comment by nblumhardt** [comment]
Thanks @merbla :-)

Just popped out a build from `master` a couple of days ago, so might hold onto this until the end of the week unless you think we need to get it out sooner?

**Pull request merged**
