### PR TITLE
leverage Array.Empty to reduce some GC

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Review by nblumhardt — APPROVED** [review]

**Comment by SimonCropp** [comment]
hmmm netstandard 1.0 doesnt have `Array.Empty`.

Options:

 * trivial to poly-fill it.
 * dont make this change
 * drop netstandard 1.0 support

@nblumhardt your call

**Comment by SimonCropp** [comment]
@nblumhardt bump

**Comment by nblumhardt** [comment]
One to include in v3? RE #1714

**Comment by SimonCropp** [comment]
@nblumhardt sounds good to me

**Pull request closed without merging**
