### PR TITLE
Added codecov.io integration

### PR DESCRIPTION
**Pull request by 304NotModified**
[Codecov.io](https://Codecov.io) is a free (for FOSS) Code coverage platform in the cloud. You can sign up with your GitHub account and add in the future badges and webhooks. 

This PR will submit the code coverage to Codecov.io

### CODE REVIEW

**Comment by nblumhardt** [comment]
Thanks Julian, I'll take a look :+1:

**Comment by 304NotModified** [comment]
If you having any question, let me know.

The results of my fork can be seen here: https://codecov.io/gh/304NotModified/serilog/tree/dev/src/Serilog

Pretty useful information IMO!

**Comment by nblumhardt** [comment]
Closing and re-opening as I think the build problem should no longer occur.

**Comment by nblumhardt** [comment]
@304NotModified what's needed in order for the results to be published to the service? Is the change in the PR sufficient? Cheers!

**Comment by nblumhardt** [comment]
@304NotModified aha, I see @codecov-io answered that question for me :-)

**Pull request merged**
