### PR TITLE
test on net5

### PR DESCRIPTION
**Pull request by SimonCropp**
Given net5 is being released in a couple of days, i updated the tests to run against it. On rtm u just need to update the global.json

### CODE REVIEW

**Comment by nblumhardt** [comment]
👍 makes sense; looks like the AppVeyor images are behind.

**Comment by SimonCropp** [comment]
have not forgotten this: Blocking issues

 * [ ] [update net5 core on ubuntu* ](https://github.com/appveyor/ci/issues/3571)
 * [ ] [dotnet 5 stable on macos ](https://github.com/appveyor/ci/issues/3565)
 * [ ] [Visual Studio 2019 16.8.1 with .NET 5 RTM](https://github.com/appveyor/ci/issues/3564)

**Comment by rafaelsc** [comment]
@SimonCropp 
Now AppVeyor have updated the Umbutu Image with NET5 working - https://www.appveyor.com/updates/2020/12/17/

And Microsoft recommends using `net5.0` instead of `net5`. I would prefer to use the recommended target framework name.

**Comment by rafaelsc** [comment]
I create a PR for your branch - https://github.com/SimonCropp/serilog/pull/1
I hope these changes make AppVeyor works

**Pull request closed without merging**
