### PR TITLE
Bash script for dotnet core.

### PR DESCRIPTION
**Pull request by merbla**
Updated the existing `build.sh` to work with dotnet core.

### CODE REVIEW

**Comment by nblumhardt** [comment]
LGTM.

**Comment by khellang** [comment]
Why was this hard coded to specific paths? Wouldn't it be better to keep the loop as it were?

**Comment by nblumhardt** [comment]
No preference personally - @merbla ?

**Comment by merbla** [comment]
@khellang @nblumhardt no good reason... #757 is the rework.

**Pull request merged**
