### PR TITLE
Code of Conduct, Contributing Guide & templates for issues and PRs

### PR DESCRIPTION
**Pull request by merbla**
* Code of Conduct
* Contributing Guide
* Issue Template from #842 
* PR template for #842

Code of Conduct notes the following references:

* https://www.contributor-covenant.org/
* https://www.contributor-covenant.org/version/1/4/code_of_conduct.md

### CODE REVIEW

**Comment by nblumhardt** [comment]
Hey, thanks for kicking this off, @merbla!

(For anyone curious - the Contributor Covenant has become a fairly common choice among Microsoft's .NET projects and the .NET Foundation projects to make clearer the implicit standards I think most of us assume when participating in a community-run project.)

Just to explore options, I zipped over to dotnet/corefx to see how they apply the CoC there; https://github.com/dotnet/corefx#community just includes the paragraph:

> This project has adopted the code of conduct defined by the [Contributor Covenant](http://contributor-covenant.org/)
to clarify expected behavior in our community. For more information, see the [.NET Foundation Code of Conduct](http://www.dotnetfoundation.org/code-of-conduct).

The `CODE_OF_CONDUCT.md` style is used by rust-lang/rust, but it seems a bit "shouty" to me :-) ... I'd be just as happy including the first sentence, with its embedded link, into the README here. What do you think?

**Comment by merbla** [comment]
@nblumhardt just to be clear do you mean link to https://www.contributor-covenant.org/version/1/4/code-of-conduct/ or to the DotNet foundation -https://dotnetfoundation.org/code-of-conduct

**Comment by nblumhardt** [comment]
@merbla I was only looking at the former - contributor-covenant.org - link, and the sentence it's embedded in.

**Comment by merbla** [comment]
@nblumhardt in the same space, extended this to include templates and contributing guide.

Rolled all into one PR due to the cross over.

**Comment by nblumhardt** [comment]
Looks great, let's merge now and nitpick later :-)

**Pull request merged**
