### PR TITLE
Fix for #196 LogContext to work cross-domain

### PR DESCRIPTION
**Pull request by gertjvr**
Had an issue today with cross-domain integration tests failing

Read [this](http://blog.stephencleary.com/2013/04/implicit-async-context-asynclocal.html) article a few days ago thought I'll try make serilog work cross-domains.

using a [failing test](https://github.com/serilog/serilog/issues/128#issuecomment-53998142) from #128 and the test seems to pass now.

### CODE REVIEW

**Comment by konste** [comment]
I wonder why it is not merged to the main branch yet. Any particular reason? I need this feature badly.

Konstantin

**Comment by nblumhardt** [comment]
Never attribute to indifference what can be explained by work and young children :-)

Taking another look at this today.

**Comment by konste** [comment]
Good answer!

Btw I checked proposed fix and it resolves cross app domain issue indeed. The biggest question is the overhead and potential side effects it may cause, so I support the idea to make it opt-in.

(sent from mobile device)

On Jan 31, 2015, at 5:24 PM, Nicholas Blumhardt <notifications@github.com<mailto:notifications@github.com>> wrote:


Never attribute to indifference what can be explained by work and young children :-)

Taking another look at this today.

-

**Comment by konste** [comment]
Forgot to ask - was it work or small children this time? ;-)

< sent from mobile device >

On Jan 31, 2015, at 5:24 PM, Nicholas Blumhardt <notifications@github.com<mailto:notifications@github.com>> wrote:


Never attribute to indifference what can be explained by work and young children :-)

Taking another look at this today.

-

**Pull request merged**
