### PR TITLE
Major version bump; opens dev for v3 development

### PR DESCRIPTION
**Pull request by nblumhardt**
I believe it's time to give the project a refresh; a new major version is a good marker for this, but I should be clear at the outset we won't be making any ecosystem-splitting breaking changes (all existing sinks, enrichers, and so on should continue to work as before).

In particular, for 3.0 I'm anticipating we:

 * Drop seriously out-of-date framework targets (`netstandard1.x`, and potentially full framework)
 * Drop obsolete APIs or upgrade obsoletions to error rather than warning where sink dependencies may exist
 * Consider behavioral changes currently recorded against the [3.0 milestone](https://github.com/serilog/serilog/milestone/13)

Along with this I think we'd ship a set of _Serilog.Extensions.*_ and _Serilog.AspNetCore_ packages that lock their versions to the framework versions they support.

Plus consider new functionality such as a baked-in `IDiagnosticContext`.

### CODE REVIEW

**Comment by SimonCropp** [comment]
@nblumhardt https://github.com/serilog/serilog/pull/1800

**Comment by SimonCropp** [comment]
@nblumhardt https://github.com/serilog/serilog/pull/1801

**Comment by nblumhardt** [comment]
@SimonCropp Nice! 👍

I think that some of these (removals of obsolete APIs) will cause enough breakage that we'll need to turn them into errors instead, but, how about we:

 1. Clobber them all, with individual PRs like your two above
 2. Finish 3.0 :-)
 3. Test the result for binary compatibility with all the Serilog sinks we can find on NuGet (I think I can automate this - may not be soon though)
 4. In problematic cases, either send upstream fixes (preferred), ignore, or at worst, reinstate/roll back the change

Sounds workable?

**Comment by SimonCropp** [comment]
@nblumhardt sounds good to me. those prs are easy to revert if we need to based on downstreams

**Pull request merged**
