### PR TITLE
Adds Serilog.Extras.FSharp

### PR DESCRIPTION
**Pull request by nblumhardt**
Implements the suggestion from @vlaci in #352

### CODE REVIEW

**Comment by nblumhardt** [comment]
Hold up... missing some build changes to generate the NUPKG

**Comment by nblumhardt** [comment]
Okay - builds and runs! @mivano @khellang @SimonCropp @merbla any chance of a quick look over?

// cc @vlaci

**Comment by vlaci** [comment]
:thumbsup:
Awesome :)

**Comment by khellang** [comment]
Looks good to me! :+1:

**Pull request merged**
